name: Verification

on:
  pull_request:
    branches:
    - master

env:
  cache-version: v1

jobs:
  #==============================================================================
  Native-Android:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Common build cache (build/BuildCache)
      uses: actions/cache@v1
      with:
        path: ./build/BuildCache
        key: ${{ env.cache-version }}-BuildCache-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Build
      run: |
        dotnet run -- dotnet run -- BuildExternalProjects Android-x86_64
        dotnet run -- BuildEngine_Android

  #==============================================================================
  Native-macOS:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Common build cache (build/BuildCache)
      uses: actions/cache@v1
      with:
        path: ./build/BuildCache
        key: ${{ env.cache-version }}-BuildCache-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Build
      run: |
        dotnet run -- BuildExternalProjects macOS
        dotnet run -- BuildEngine_macOS

  #==============================================================================
  Native-iOS:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Common build cache (build/BuildCache)
      uses: actions/cache@v1
      with:
        path: ./build/BuildCache
        key: ${{ env.cache-version }}-BuildCache-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Build
      run: |
        dotnet run -- BuildExternalProjects iOS-OS64
        dotnet run -- BuildExternalProjects iOS-SIMULATOR64
        dotnet run -- BuildEngine_iOS
      
  #==============================================================================
  Native-MSVC2019-x64-MT:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Cache (build/BuildCache)
      uses: actions/cache@v1
      with:
        path: ./build/MSVC2019-x64-MT/BuildCache
        key: ${{ env.cache-version }}-BuildCache-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Cache (build/MSVC2019-x64-MT/ExternalInstall)
      uses: actions/cache@v1
      with:
        path: ./build/MSVC2019-x64-MT/ExternalInstall
        key: ${{ env.cache-version }}-ExternalInstall-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Build
      run: |
        dotnet run -- BuildExternalProjects MSVC2019-x64-MT
        dotnet run -- BuildEngine_MSVC MSVC2019-x64-MT
      
    - uses: actions/upload-artifact@v1
      with:
        name: LuminoEngine-MSVC2019-x64-MT
        path: ./build/MSVC2019-x64-MT/EngineInstall

  #==============================================================================
  Ruby:
    needs: Native-MSVC2019-x64-MT
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        architecture: 'x64'

    - uses: actions/download-artifact@v1
      with:
        name: LuminoEngine-MSVC2019-x64-MT
        path: ./build/MSVC2019-x64-MT/EngineInstall

    - name: Build and test with Rake
      run: |
        ls ./build/MSVC2019-x64-MT/EngineInstall
        ls ./build/MSVC2019-x64-MT/EngineInstall/bin
        gem install bundler
        dotnet run -- MakePackage_Ruby

