name: Verification

on:
  pull_request:
    branches:
    - master

jobs:
  Native-MSVC2017-x64-MT:
    runs-on: windows-2016 # for VS2017

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Install vulkan-sdk
      run:  |
        choco install vulkan-sdk
        refreshenv
        cat C:\ProgramData\chocolatey\logs\chocolatey.log
        C:\VulkanSDK\1.1.126.0\Bin\vkcubepp

    - name: Build
      run: dotnet run -- BuildEngine_MSVC MSVC2017-x64-MT
      
