name: Verification

on:
  pull_request:
    branches:
    - master

env:
  cache-version: v1

jobs:
  Ruby:
    needs: Native-MSVC2017-x64-MT
    runs-on: windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
        architecture: 'x64'

    - uses: actions/download-artifact@v1
      with:
        name: LuminoEngine-MSVC2017-x64-MT
        path: ./build/MSVC2017-x64-MT/EngineInstall

    - name: Build and test with Rake
      run: dotnet run -- MakePackage_Ruby
