name: Package

on:
  pull_request:
    branches:
    - master

env:
  cache-version: v1

jobs:
  #==============================================================================
  Native-Windows:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Common build cache (build/BuildCache)
      uses: actions/cache@v1
      with:
        path: ./build/BuildCache
        key: ${{ env.cache-version }}-BuildCache-${{ hashFiles('**/BuildExternalProjects.cs') }}
            
    - name: Build
      run: |
        dotnet run -- BuildExternalProjects Android-x86_64
        dotnet run -- BuildExternalProjects Android-x86
        dotnet run -- BuildExternalProjects Android-arm64-v8a
        dotnet run -- BuildExternalProjects Android-armeabi-v7a
        dotnet run -- BuildExternalProjects Emscripten
        dotnet run -- BuildExternalProjects MSVC2019-x64-MT
        dotnet run -- BuildEngine_Android
        dotnet run -- BuildEngine_Emscripten
        dotnet run -- BuildEngine_MSVC MSVC2019-x64-MT
        dotnet run -- BuildEngine_Android
        dotnet run -- MakeNativePackage
        dotnet run -- MakeInstaller_Win32

    - uses: actions/upload-artifact@v1
      with:
        name: Lumino-latest-Windows.msi
        path: ./build/Lumino-latest-Windows.msi

    - uses: actions/upload-artifact@v1
      with:
        name: Lumino-latest-Windows.zip
        path: ./build/Lumino-latest-Windows.zip
