name: WebDocument (Latest build)

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Preparation
      run: git rev-parse --short HEAD > docs/WebDocument/template/partials/revision_mark.tmpl.partial

    - name: Build
      uses: nikeee/docfx-action@master
      with:
        args: docs/WebDocument/docfx.json

    - name: Deploy
      env:
        CI_PUSH_TOKEN: ${{ secrets.CI_PUSH_TOKEN }}
      run: |
        cd docs/WebDocument
        git clone https://${GITHUB_ACTOR}:${CI_PUSH_TOKEN}@github.com/lriki/lriki.github.io _docs_repo
        rm -rf _docs_repo/lumino/latest-lumino-webdocs
        cp -rf _site _docs_repo/lumino/latest-lumino-webdocs
        cd _docs_repo
        ls 
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config core.autoCRLF false
        git add .
        git commit -m '[CI] Deploy to GitHub Pages'
        git push origin master

